"""EdgeTTS adapter and reusable synthesis helpers.

All temporary audio is written below the workspace on E: and removed after it
has been decoded.  The helpers in this module are also used by the HTTP API so
the digital-human pipeline and the preview page share exactly the same rules.
"""

from __future__ import annotations

import asyncio
import json
import re
import time
import uuid
from io import BytesIO
from pathlib import Path

import edge_tts
import numpy as np
import resampy
import soundfile as sf

from registry import register
from utils.logger import logger
from .base_tts import BaseTTS, State


DEFAULT_VOICE = "zh-CN-XiaoxiaoNeural"
DEFAULT_RATE = "+0%"
DEFAULT_VOLUME = "+0%"
DEFAULT_PITCH = "+0Hz"
DEFAULT_TIMEOUT_SECONDS = 30
MAX_SEGMENT_CHARS = 280
MAX_TEXT_CHARS = 20_000
CACHE_MAX_AGE_SECONDS = 3600

_VOICE_RE = re.compile(r"^[A-Za-z0-9-]{3,100}$")
_PERCENT_RE = re.compile(r"^[+-]\d{1,3}%$")
_PITCH_RE = re.compile(r"^[+-]\d{1,4}Hz$")
_SENTENCE_RE = re.compile(r"(?<=[。！？!?；;\n])")


class EdgeTTSError(RuntimeError):
    """A safe, user-facing EdgeTTS error."""


def edge_temp_dir() -> Path:
    """Return the dedicated EdgeTTS directory below E:\\SZR\\.tmp."""
    workspace_dir = Path(__file__).resolve().parents[2]
    return workspace_dir / ".tmp" / "edge-tts"


def _validate_percent(value: str, field_name: str) -> str:
    value = str(value).strip()
    if not _PERCENT_RE.fullmatch(value):
        raise EdgeTTSError(f"{field_name}格式无效，应类似 +0% 或 -10%")
    number = int(value[:-1])
    if not -100 <= number <= 100:
        raise EdgeTTSError(f"{field_name}必须在 -100% 到 +100% 之间")
    return value


def validate_edge_settings(
    voice: str = DEFAULT_VOICE,
    rate: str = DEFAULT_RATE,
    volume: str = DEFAULT_VOLUME,
    pitch: str = DEFAULT_PITCH,
    timeout_seconds: float = DEFAULT_TIMEOUT_SECONDS,
) -> dict:
    voice = str(voice or DEFAULT_VOICE).strip()
    if not _VOICE_RE.fullmatch(voice):
        raise EdgeTTSError("语音名称格式无效")

    pitch = str(pitch).strip()
    if not _PITCH_RE.fullmatch(pitch):
        raise EdgeTTSError("音调格式无效，应类似 +0Hz 或 -20Hz")
    pitch_number = int(pitch[:-2])
    if not -1000 <= pitch_number <= 1000:
        raise EdgeTTSError("音调必须在 -1000Hz 到 +1000Hz 之间")

    try:
        timeout = float(timeout_seconds)
    except (TypeError, ValueError) as exc:
        raise EdgeTTSError("超时时间必须是数字") from exc
    if not 1 <= timeout <= 120:
        raise EdgeTTSError("超时时间必须在 1 到 120 秒之间")

    return {
        "voice": voice,
        "rate": _validate_percent(rate, "语速"),
        "volume": _validate_percent(volume, "音量"),
        "pitch": pitch,
        "timeout_seconds": timeout,
    }


def speed_to_rate(speed: float) -> str:
    """Convert OpenAI-compatible speed (1.0 = normal) to Edge rate."""
    try:
        speed_value = float(speed)
    except (TypeError, ValueError) as exc:
        raise EdgeTTSError("语速必须是数字") from exc
    if not 0.25 <= speed_value <= 2.0:
        raise EdgeTTSError("语速必须在 0.25 到 2.0 之间")
    percentage = round((speed_value - 1.0) * 100)
    return f"{percentage:+d}%"


def split_text_safely(text: str, max_chars: int = MAX_SEGMENT_CHARS) -> list[str]:
    """Split long text on sentence boundaries, then hard-wrap safely."""
    normalized = str(text or "").strip()
    if not normalized:
        raise EdgeTTSError("文本不能为空")
    if len(normalized) > MAX_TEXT_CHARS:
        raise EdgeTTSError(f"文本过长，最多允许 {MAX_TEXT_CHARS} 个字符")
    if max_chars < 20:
        raise ValueError("max_chars must be at least 20")

    segments: list[str] = []
    current = ""
    for sentence in _SENTENCE_RE.split(normalized):
        sentence = sentence.strip()
        if not sentence:
            continue
        if len(current) + len(sentence) <= max_chars:
            current += sentence
            continue
        if current:
            segments.append(current)
            current = ""
        while len(sentence) > max_chars:
            split_at = sentence.rfind("，", 0, max_chars + 1)
            if split_at < max_chars // 3:
                split_at = sentence.rfind(",", 0, max_chars + 1)
            if split_at < max_chars // 3:
                split_at = max_chars
            else:
                split_at += 1
            segments.append(sentence[:split_at].strip())
            sentence = sentence[split_at:].strip()
        current = sentence
    if current:
        segments.append(current)
    return segments


def cleanup_expired_cache(
    cache_dir: Path | None = None,
    max_age_seconds: int = CACHE_MAX_AGE_SECONDS,
) -> int:
    """Delete only expired files generated by this adapter."""
    directory = (cache_dir or edge_temp_dir()).resolve()
    if not directory.exists():
        return 0
    removed = 0
    cutoff = time.time() - max_age_seconds
    for candidate in directory.glob("edge-*.mp3"):
        try:
            resolved = candidate.resolve()
            if resolved.parent == directory and resolved.stat().st_mtime < cutoff:
                resolved.unlink()
                removed += 1
        except FileNotFoundError:
            continue
        except OSError:
            logger.warning("EdgeTTS expired cache cleanup skipped for %s", candidate.name)
    return removed


async def list_edge_voices(timeout_seconds: float = DEFAULT_TIMEOUT_SECONDS) -> list[dict]:
    settings = validate_edge_settings(timeout_seconds=timeout_seconds)
    try:
        voices = await asyncio.wait_for(
            edge_tts.list_voices(), timeout=settings["timeout_seconds"]
        )
    except asyncio.TimeoutError as exc:
        raise EdgeTTSError("获取语音列表超时，请检查网络后重试") from exc
    except Exception as exc:
        raise EdgeTTSError("无法获取语音列表，请检查网络连接") from exc
    return sorted(voices, key=lambda item: (item.get("Locale", ""), item.get("ShortName", "")))


async def _save_segment(segment: str, target: Path, settings: dict) -> None:
    communicate = edge_tts.Communicate(
        segment,
        settings["voice"],
        rate=settings["rate"],
        volume=settings["volume"],
        pitch=settings["pitch"],
        connect_timeout=min(10, int(settings["timeout_seconds"])),
        receive_timeout=int(settings["timeout_seconds"]),
    )
    await asyncio.wait_for(
        communicate.save(str(target)), timeout=settings["timeout_seconds"]
    )


async def synthesize_edge_pcm_async(
    text: str,
    voice: str = DEFAULT_VOICE,
    rate: str = DEFAULT_RATE,
    volume: str = DEFAULT_VOLUME,
    pitch: str = DEFAULT_PITCH,
    timeout_seconds: float = DEFAULT_TIMEOUT_SECONDS,
    sample_rate: int = 16_000,
) -> np.ndarray:
    settings = validate_edge_settings(voice, rate, volume, pitch, timeout_seconds)
    segments = split_text_safely(text)
    cache_dir = edge_temp_dir()
    cache_dir.mkdir(parents=True, exist_ok=True)
    cleanup_expired_cache(cache_dir)

    audio_parts: list[np.ndarray] = []
    for segment in segments:
        target = cache_dir / f"edge-{uuid.uuid4().hex}.mp3"
        try:
            last_error: Exception | None = None
            for attempt in range(2):
                try:
                    await _save_segment(segment, target, settings)
                    last_error = None
                    break
                except Exception as exc:
                    last_error = exc
                    if attempt == 0:
                        await asyncio.sleep(0.5)
            if last_error is not None:
                raise last_error

            stream, source_rate = sf.read(target, dtype="float32")
            if stream.ndim > 1:
                stream = stream[:, 0]
            if source_rate != sample_rate and stream.size:
                stream = resampy.resample(
                    x=stream, sr_orig=source_rate, sr_new=sample_rate
                ).astype(np.float32)
            audio_parts.append(np.asarray(stream, dtype=np.float32))
        except asyncio.TimeoutError as exc:
            raise EdgeTTSError("语音合成超时，请检查网络后重试") from exc
        except EdgeTTSError:
            raise
        except Exception as exc:
            raise EdgeTTSError("语音合成失败，请检查网络连接后重试") from exc
        finally:
            try:
                target.unlink(missing_ok=True)
            except OSError:
                logger.warning("EdgeTTS temporary file cleanup skipped: %s", target.name)

    cleanup_expired_cache(cache_dir)
    if not audio_parts:
        raise EdgeTTSError("语音合成未返回有效音频")
    return np.concatenate(audio_parts)


def synthesize_edge_pcm(**kwargs) -> np.ndarray:
    return asyncio.run(synthesize_edge_pcm_async(**kwargs))


def pcm_to_wav_bytes(pcm: np.ndarray, sample_rate: int = 16_000) -> bytes:
    output = BytesIO()
    sf.write(output, pcm, sample_rate, format="WAV", subtype="PCM_16")
    return output.getvalue()


@register("tts", "edgetts")
class EdgeTTS(BaseTTS):
    def _settings_from_event(self, textevent: dict) -> dict:
        payload = textevent.get("tts") or {}
        voice = (
            payload.get("voice")
            or payload.get("ref_file")
            or getattr(self.opt, "EDGE_TTS_VOICE", "")
            or getattr(self.opt, "REF_FILE", "")
            or DEFAULT_VOICE
        )
        return validate_edge_settings(
            voice=voice,
            rate=payload.get("rate", getattr(self.opt, "EDGE_TTS_RATE", DEFAULT_RATE)),
            volume=payload.get(
                "volume", getattr(self.opt, "EDGE_TTS_VOLUME", DEFAULT_VOLUME)
            ),
            pitch=payload.get(
                "pitch", getattr(self.opt, "EDGE_TTS_PITCH", DEFAULT_PITCH)
            ),
            timeout_seconds=getattr(
                self.opt, "TTS_TIMEOUT_SECONDS", DEFAULT_TIMEOUT_SECONDS
            ),
        )

    def txt_to_audio(self, msg: tuple[str, dict]):
        text, textevent = msg
        started = time.time()
        try:
            settings = self._settings_from_event(textevent)
            stream = synthesize_edge_pcm(
                text=text, sample_rate=self.sample_rate, **settings
            )
            elapsed = time.time() - started
            if hasattr(self.parent, "runtime_metrics"):
                self.parent.runtime_metrics["tts_seconds"] = round(elapsed, 4)
            logger.info("EdgeTTS synthesis completed in %.4fs", elapsed)
        except EdgeTTSError as exc:
            logger.error("EdgeTTS request failed: %s", exc)
            if hasattr(self.parent, "runtime_metrics"):
                self.parent.runtime_metrics["request_active"] = False
            if hasattr(self.parent, "send_msg"):
                self.parent.send_msg(json.dumps(
                    {"type": "tts", "status": "error", "message": str(exc)},
                    ensure_ascii=False,
                ))
            return
        except Exception:
            logger.exception("Unexpected EdgeTTS failure")
            if hasattr(self.parent, "runtime_metrics"):
                self.parent.runtime_metrics["request_active"] = False
            if hasattr(self.parent, "send_msg"):
                self.parent.send_msg(json.dumps(
                    {
                        "type": "tts",
                        "status": "error",
                        "message": "语音合成失败，服务仍在运行，请稍后重试",
                    },
                    ensure_ascii=False,
                ))
            return

        streamlen = stream.shape[0]
        idx = 0
        while streamlen >= self.chunk and self.state == State.RUNNING:
            streamlen -= self.chunk
            eventpoint = {}
            if idx == 0:
                eventpoint = {"status": "start", "text": text}
                request_started = getattr(self.parent, "runtime_metrics", {}).get(
                    "request_started_at"
                )
                if request_started:
                    self.parent.runtime_metrics["start_total_seconds"] = round(
                        time.perf_counter() - request_started, 4
                    )
            elif streamlen < self.chunk:
                eventpoint = {"status": "end", "text": text}
            eventpoint.update(**textevent)
            self.parent.put_audio_frame(stream[idx : idx + self.chunk], eventpoint)
            idx += self.chunk
